feat: allow non-cli execution
nodejs/api-docs-tooling pull request #137
Opened 2024-11-02 16:48 UTC by RedYetiDev

## Description

This PR adds the ability to execute this from another JS file, without the use of the CLI. That way, `man-page`, and any future generators wouldn't be limited to the CLI for execution

## Validation

Verify that all execution is working as planned.

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/api-docs-tooling/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [-] I've covered new added functionality with unit tests if necessary.

2024-11-03 09:48 UTC, AugustinMauroy commented on package.json
> +  "type": "module",
If we use this key no needed to have .mjs ?

2024-11-04 18:03 UTC, AugustinMauroy approved these changes
LGMT !

2024-11-04 18:13 UTC, flakey5 approved these changes

2024-11-05 20:00 UTC, RedYetiDev commented
Thanks for the approvals! Once this lands, I'll be able to implement it with https://github.com/nodejs/node/pull/55268, which will really bring the new man-page generator into the core :-)!

2024-11-05 20:02 UTC, AugustinMauroy commented
cc @ovflowd

2024-11-05 20:08 UTC, ovflowd requested changes
Ill explain better why Im against this implementation later, although Im +1 with the idea of allowing this to be consumed within JS, I just want to prevent someone to merge this for the time being.

2024-11-05 23:02 UTC, ovflowd commented
Alrighty, I'm back 👋

So pretty much my idea here is:

Instead of exporting an one does everything function, cli.js should still do exactly what it is doing, parsing cli args and doing whatever it needs to be done to be able to run from the CLI.

On index.js simply only export all the functions that exist on the other modules. My reasoning is that  by exporting this nebulous function it creates a black box and prevents people from actually importing each module.

Hence on node core you'll simply import the exports of this package and create your own instance of whatever you need, which allows you even to make it specific for the needs of man doc gen.

Also don't forget to update package.json so that only the index.mjs file is exported on the module. I also would say this file should be .mjs

2024-11-08 16:52 UTC, RedYetiDev commented
Thanks for your feedback. I've updated this to just export the other files. PTAL when you get a change :-)

2024-11-08 17:14 UTC, flakey5 approved these changes

2024-11-08 23:23 UTC, ovflowd approved these changes
Here we go :)

2024-11-08 23:23 UTC, ovflowd commented
Thank you, @RedYetiDev and apologies for blocking you!

2024-11-16 14:49 UTC, merged